server:
  port: 8080

spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/clinic_db'
    username: 'root'
    password: 'admin'

  mandatory-file-encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  messages:
    basename: messages/messages, messages/messages_en, messages/messages_ua

  data:
    web:
      pageable:
        default-page-size: 10


